name: Bug report
description: Something isn't working
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        Please include *repro steps* and your environment so we can fix it quickly.
  - type: input
    id: version
    attributes:
      label: create-mcp-server-kit version
      placeholder: "0.1.0"
    validations:
      required: false
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "node --version"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact commands you ran.
      placeholder: |
        node ./bin/create-mcp-server-kit.js my-mcp-server
        cd my-mcp-server
        npm install
        npm run build
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / error output
      render: shell
    validations:
      required: true


